import { Talent } from "./types";

export const dummyTalents: Talent[] = [
  {
    id: "1",
    name: "Tran Nguyen",
    role: "프론트엔드",
    years_exp: 3,
    location: "호치민",
    ovr_score: 89,
    ovr_grade: "S",
    top_skills: ["React", "TypeScript"],
    korean_level: 4,
    desired_salary_krw: 150,
    availability: "immediate",
    ktc_comment:
      "한국 기업 협업 경험 풍부. 의사소통 명료하고 일정 준수 우수.",
    abilities: {
      technical: 88,
      korean: 85,
      english: 78,
      collaboration: 92,
      stability: 90,
      growth: 86,
    },
    detailed_skills: [
      { name: "React", score: 92, type: "core" },
      { name: "TypeScript", score: 85, type: "core" },
      { name: "Next.js", score: 80, type: "core" },
      { name: "Tailwind CSS", score: 78, type: "sub" },
      { name: "Figma", score: 65, type: "sub" },
    ],
    career_history: [
      { tier: "Tier 1 한국계 IT 기업", position: "시니어 프론트엔드", startDate: "2022.03", endDate: "current", current: true },
      { tier: "Tier 2 베트남 로컬 스타트업", position: "프론트엔드 개발자", startDate: "2020.06", endDate: "2022.02", current: false },
      { tier: "Tier 3 SI 외주사", position: "주니어 개발자", startDate: "2019.01", endDate: "2020.05", current: false },
    ],
    tags: ["한국어 비즈니스", "원격 가능", "한국 기업 경험"],
  },
  {
    id: "2",
    name: "Hoang Le",
    role: "백엔드",
    years_exp: 4,
    location: "하노이",
    ovr_score: 85,
    ovr_grade: "S",
    top_skills: ["Java", "Spring Boot"],
    korean_level: 3,
    desired_salary_krw: 180,
    availability: "negotiable",
    ktc_comment:
      "대규모 트래픽 처리 경험 보유. 꼼꼼한 성격으로 코드 리뷰에 적극적.",
    abilities: {
      technical: 90,
      korean: 72,
      english: 82,
      collaboration: 78,
      stability: 88,
      growth: 80,
    },
    detailed_skills: [
      { name: "Java", score: 90, type: "core" },
      { name: "Spring Boot", score: 88, type: "core" },
      { name: "MySQL", score: 82, type: "core" },
      { name: "AWS", score: 75, type: "sub" },
      { name: "Docker", score: 70, type: "sub" },
    ],
    career_history: [
      { tier: "Tier 1 한국계 IT 기업", position: "백엔드 리드", startDate: "2021.01", endDate: "current", current: true },
      { tier: "Tier 1 글로벌 기업 베트남 지사", position: "시니어 백엔드", startDate: "2018.06", endDate: "2020.12", current: false },
      { tier: "Tier 2 베트남 로컬 기업", position: "백엔드 개발자", startDate: "2017.03", endDate: "2018.05", current: false },
    ],
    tags: ["대규모 트래픽", "코드 리뷰 문화", "MSA 경험"],
  },
  {
    id: "3",
    name: "Minh Tran",
    role: "UI/UX 디자이너",
    years_exp: 3,
    location: "호치민",
    ovr_score: 87,
    ovr_grade: "S",
    top_skills: ["Figma", "Prototyping"],
    korean_level: 5,
    desired_salary_krw: 130,
    availability: "immediate",
    ktc_comment:
      "차분하고 논리적인 디자이너. 한국어 능통하여 커뮤니케이션 비용 매우 낮음.",
    abilities: {
      technical: 82,
      korean: 95,
      english: 70,
      collaboration: 90,
      stability: 85,
      growth: 88,
    },
    detailed_skills: [
      { name: "Figma", score: 95, type: "core" },
      { name: "Prototyping", score: 88, type: "core" },
      { name: "Design System", score: 82, type: "core" },
      { name: "HTML/CSS", score: 65, type: "sub" },
      { name: "Photoshop", score: 60, type: "sub" },
    ],
    career_history: [
      { tier: "Tier 1 한국계 스타트업", position: "리드 디자이너", startDate: "2023.01", endDate: "current", current: true },
      { tier: "Tier 2 베트남 에이전시", position: "UI/UX 디자이너", startDate: "2021.03", endDate: "2022.12", current: false },
      { tier: "프리랜서", position: "웹 디자이너", startDate: "2020.06", endDate: "2021.02", current: false },
    ],
    tags: ["한국어 능통", "디자인 시스템", "스타트업 경험"],
  },
  {
    id: "4",
    name: "Duc Pham",
    role: "풀스택",
    years_exp: 3,
    location: "다낭",
    ovr_score: 78,
    ovr_grade: "A",
    top_skills: ["Node.js", "React"],
    korean_level: 2,
    desired_salary_krw: 140,
    availability: "negotiable",
    ktc_comment:
      "프론트와 백엔드를 균형 있게 다루는 타입. 단독 작업보다 팀 협업에서 강점.",
    abilities: {
      technical: 80,
      korean: 55,
      english: 78,
      collaboration: 82,
      stability: 75,
      growth: 76,
    },
    detailed_skills: [
      { name: "Node.js", score: 82, type: "core" },
      { name: "React", score: 78, type: "core" },
      { name: "PostgreSQL", score: 75, type: "core" },
      { name: "Express", score: 72, type: "core" },
      { name: "AWS", score: 65, type: "sub" },
    ],
    career_history: [
      { tier: "Tier 2 한국계 중소기업", position: "풀스택 개발자", startDate: "2021.06", endDate: "current", current: true },
      { tier: "Tier 2 베트남 로컬 스타트업", position: "웹 개발자", startDate: "2019.03", endDate: "2021.05", current: false },
      { tier: "Tier 3 외주 개발사", position: "주니어 개발자", startDate: "2018.01", endDate: "2019.02", current: false },
    ],
    tags: ["풀스택", "원격 가능", "팀 플레이어"],
  },
  {
    id: "5",
    name: "An Vo",
    role: "백엔드",
    years_exp: 2,
    location: "호치민",
    ovr_score: 76,
    ovr_grade: "A",
    top_skills: ["Python", "FastAPI"],
    korean_level: 3,
    desired_salary_krw: 180,
    availability: "immediate",
    ktc_comment:
      "빠른 학습 속도와 문제 해결 능력이 강점. 안정성보다는 성장에 무게.",
    abilities: {
      technical: 78,
      korean: 68,
      english: 80,
      collaboration: 72,
      stability: 65,
      growth: 88,
    },
    detailed_skills: [
      { name: "Python", score: 85, type: "core" },
      { name: "FastAPI", score: 80, type: "core" },
      { name: "PostgreSQL", score: 72, type: "core" },
      { name: "Docker", score: 68, type: "sub" },
      { name: "Redis", score: 60, type: "sub" },
    ],
    career_history: [
      { tier: "Tier 2 베트남 테크 스타트업", position: "백엔드 개발자", startDate: "2022.06", endDate: "current", current: true },
      { tier: "Tier 3 SI 외주사", position: "주니어 개발자", startDate: "2021.01", endDate: "2022.05", current: false },
    ],
    tags: ["빠른 학습", "Python 전문", "스타트업 문화"],
  },
  {
    id: "6",
    name: "Khanh Nguyen",
    role: "DevOps",
    years_exp: 5,
    location: "하노이",
    ovr_score: 80,
    ovr_grade: "A",
    top_skills: ["AWS", "Docker"],
    korean_level: 4,
    desired_salary_krw: 190,
    availability: "negotiable",
    ktc_comment:
      "인프라 전반에 대한 깊은 이해. 장애 대응이 빠르고 문서화를 잘함.",
    abilities: {
      technical: 85,
      korean: 80,
      english: 75,
      collaboration: 76,
      stability: 92,
      growth: 70,
    },
    detailed_skills: [
      { name: "AWS", score: 90, type: "core" },
      { name: "Docker", score: 88, type: "core" },
      { name: "Kubernetes", score: 82, type: "core" },
      { name: "Terraform", score: 75, type: "sub" },
      { name: "Prometheus", score: 68, type: "sub" },
    ],
    career_history: [
      { tier: "Tier 1 한국계 IT 대기업", position: "시니어 DevOps 엔지니어", startDate: "2020.01", endDate: "current", current: true },
      { tier: "Tier 1 글로벌 기업 베트남 지사", position: "인프라 엔지니어", startDate: "2017.06", endDate: "2019.12", current: false },
      { tier: "Tier 2 베트남 호스팅 기업", position: "시스템 관리자", startDate: "2016.03", endDate: "2017.05", current: false },
    ],
    tags: ["클라우드 전문", "장애 대응", "문서화 우수"],
  },
  {
    id: "7",
    name: "Linh Huynh",
    role: "프론트엔드",
    years_exp: 1,
    location: "호치민",
    ovr_score: 74,
    ovr_grade: "A",
    top_skills: ["Vue.js", "JavaScript"],
    korean_level: 1,
    desired_salary_krw: 150,
    availability: "immediate",
    ktc_comment:
      "성실하고 피드백 수용 자세가 좋음. 한국어는 기초 수준이나 영어 소통 가능.",
    abilities: {
      technical: 72,
      korean: 35,
      english: 75,
      collaboration: 78,
      stability: 70,
      growth: 85,
    },
    detailed_skills: [
      { name: "Vue.js", score: 78, type: "core" },
      { name: "JavaScript", score: 75, type: "core" },
      { name: "HTML/CSS", score: 80, type: "core" },
      { name: "Vuetify", score: 65, type: "sub" },
      { name: "Git", score: 60, type: "sub" },
    ],
    career_history: [
      { tier: "Tier 2 베트남 로컬 스타트업", position: "프론트엔드 개발자", startDate: "2023.06", endDate: "current", current: true },
      { tier: "Tier 3 웹 에이전시", position: "인턴 → 주니어", startDate: "2022.01", endDate: "2023.05", current: false },
    ],
    tags: ["성장형 인재", "영어 소통", "가성비"],
  },
  {
    id: "8",
    name: "Phuc Quach",
    role: "데이터 분석가",
    years_exp: 3,
    location: "하노이",
    ovr_score: 75,
    ovr_grade: "A",
    top_skills: ["SQL", "Python"],
    korean_level: 2,
    desired_salary_krw: 180,
    availability: "employed",
    ktc_comment:
      "데이터 기반 의사결정에 강점. 현직 중이나 좋은 기회에 이직 의향 있음.",
    abilities: {
      technical: 78,
      korean: 50,
      english: 82,
      collaboration: 70,
      stability: 80,
      growth: 75,
    },
    detailed_skills: [
      { name: "SQL", score: 88, type: "core" },
      { name: "Python", score: 82, type: "core" },
      { name: "Tableau", score: 75, type: "core" },
      { name: "PowerBI", score: 68, type: "sub" },
      { name: "Excel", score: 72, type: "sub" },
    ],
    career_history: [
      { tier: "Tier 1 글로벌 기업 베트남 지사", position: "데이터 분석가", startDate: "2022.01", endDate: "current", current: true },
      { tier: "Tier 2 베트남 핀테크", position: "주니어 분석가", startDate: "2020.03", endDate: "2021.12", current: false },
      { tier: "Tier 3 리서치 회사", position: "리서치 어시스턴트", startDate: "2019.06", endDate: "2020.02", current: false },
    ],
    tags: ["데이터 분석", "대시보드", "BI 도구"],
  },
  {
    id: "9",
    name: "Bao Truong",
    role: "프론트엔드",
    years_exp: 2,
    location: "다낭",
    ovr_score: 72,
    ovr_grade: "A",
    top_skills: ["React Native", "TypeScript"],
    korean_level: 3,
    desired_salary_krw: 130,
    availability: "negotiable",
    ktc_comment:
      "모바일 크로스플랫폼 개발 전문. 차분한 성격으로 장기 프로젝트에 적합.",
    abilities: {
      technical: 75,
      korean: 65,
      english: 72,
      collaboration: 80,
      stability: 82,
      growth: 70,
    },
    detailed_skills: [
      { name: "React Native", score: 82, type: "core" },
      { name: "TypeScript", score: 78, type: "core" },
      { name: "React", score: 75, type: "core" },
      { name: "Firebase", score: 68, type: "sub" },
      { name: "iOS/Android", score: 60, type: "sub" },
    ],
    career_history: [
      { tier: "Tier 2 한국계 중소기업", position: "모바일 개발자", startDate: "2022.03", endDate: "current", current: true },
      { tier: "Tier 2 베트남 모바일 스타트업", position: "프론트엔드 개발자", startDate: "2020.09", endDate: "2022.02", current: false },
    ],
    tags: ["모바일 전문", "크로스플랫폼", "장기 근속"],
  },
  {
    id: "10",
    name: "Son Vu",
    role: "백엔드",
    years_exp: 2,
    location: "호치민",
    ovr_score: 65,
    ovr_grade: "B",
    top_skills: ["Go", "PostgreSQL"],
    korean_level: 5,
    desired_salary_krw: 110,
    availability: "negotiable",
    ktc_comment:
      "한국어 능통. 기술적으로는 성장 중이나 소통 능력이 뛰어나 팀 적응이 빠름.",
    abilities: {
      technical: 62,
      korean: 92,
      english: 60,
      collaboration: 85,
      stability: 68,
      growth: 78,
    },
    detailed_skills: [
      { name: "Go", score: 68, type: "core" },
      { name: "PostgreSQL", score: 65, type: "core" },
      { name: "REST API", score: 70, type: "core" },
      { name: "Git", score: 62, type: "sub" },
      { name: "Linux", score: 58, type: "sub" },
    ],
    career_history: [
      { tier: "Tier 2 한국계 중소기업", position: "백엔드 개발자", startDate: "2023.01", endDate: "current", current: true },
      { tier: "Tier 3 외주 개발사", position: "주니어 개발자", startDate: "2021.06", endDate: "2022.12", current: false },
    ],
    tags: ["한국어 능통", "소통 우수", "성장형"],
  },
  {
    id: "11",
    name: "Chi Dang",
    role: "UI/UX 디자이너",
    years_exp: 2,
    location: "하노이",
    ovr_score: 68,
    ovr_grade: "B",
    top_skills: ["Sketch", "Adobe XD"],
    korean_level: 4,
    desired_salary_krw: 120,
    availability: "immediate",
    ktc_comment:
      "꼼꼼한 작업 스타일. 시스템 디자인보다 비주얼 디자인에 강점.",
    abilities: {
      technical: 65,
      korean: 78,
      english: 62,
      collaboration: 75,
      stability: 72,
      growth: 70,
    },
    detailed_skills: [
      { name: "Sketch", score: 78, type: "core" },
      { name: "Adobe XD", score: 75, type: "core" },
      { name: "Photoshop", score: 80, type: "core" },
      { name: "Illustrator", score: 68, type: "sub" },
      { name: "HTML/CSS", score: 55, type: "sub" },
    ],
    career_history: [
      { tier: "Tier 2 베트남 에이전시", position: "UI 디자이너", startDate: "2022.06", endDate: "current", current: true },
      { tier: "프리랜서", position: "그래픽 디자이너", startDate: "2021.03", endDate: "2022.05", current: false },
    ],
    tags: ["비주얼 디자인", "꼼꼼한 작업", "한국어 가능"],
  },
  {
    id: "12",
    name: "Gia Bao",
    role: "QA",
    years_exp: 1,
    location: "호치민",
    ovr_score: 58,
    ovr_grade: "C",
    top_skills: ["Selenium", "Cypress"],
    korean_level: 1,
    desired_salary_krw: 100,
    availability: "employed",
    ktc_comment:
      "테스트 자동화에 관심이 많은 주니어. 영어 소통 가능, 한국어는 학습 초기 단계.",
    abilities: {
      technical: 55,
      korean: 30,
      english: 70,
      collaboration: 65,
      stability: 60,
      growth: 72,
    },
    detailed_skills: [
      { name: "Selenium", score: 65, type: "core" },
      { name: "Cypress", score: 60, type: "core" },
      { name: "Jest", score: 55, type: "core" },
      { name: "SQL", score: 50, type: "sub" },
      { name: "Postman", score: 58, type: "sub" },
    ],
    career_history: [
      { tier: "Tier 2 베트남 로컬 기업", position: "QA 엔지니어", startDate: "2023.06", endDate: "current", current: true },
      { tier: "Tier 3 외주 개발사", position: "테스터", startDate: "2022.09", endDate: "2023.05", current: false },
    ],
    tags: ["테스트 자동화", "영어 소통", "가성비"],
  },
];
