// 히어로 하드코딩 인재 (랜딩 히어로 + 상세 페이지 공유)
// ⚠️ 여기 수정하면 히어로 카드/상세 페이지에 함께 반영됩니다.

export type HeroTalent = {
  id: string;
  name: string;
  role: string;
  headline: string | null;
  photo_url: string | null;
  school: string | null;
  schoolElite: boolean;
  schoolTier: string | null;
  company: string | null;
  companyElite: boolean;
  companyDomain: string | null;
  yoeYears: number | null;
  location: string | null;
  skills: string[];
  // 어학/소통 능력 (예: "영어 업무 가능 · 한국어 초급", "TOEIC 850"). 데이터 없으면 "조사 중" 노출
  language?: string | null;
  // 이력서/포트폴리오 원본 링크 (상세 페이지 "포트폴리오 보기" 버튼용)
  portfolioUrl?: string | null;
};

export const HERO_TALENTS: HeroTalent[] = [
  {
    id: "hero-1",
    name: "Trần Minh Hưng",
    role: "Senior QA Engineer",
    headline: "삼성 출신 /n 시니어 QA 엔지니어",
    photo_url: "/HERO%20PROFILE.png",
    school: "Ho Chi Minh University of Technology",
    schoolElite: true,
    schoolTier: "top",
    company: "Samsung",
    companyElite: true,
    companyDomain: "samsung.com",
    yoeYears: 5,
    location: "베트남 호치민",
    skills: ["Manual Testing", "API Testing", "Test Case Design", "Agile/Scrum"],
    language: "IELTS 7.0 · TOEIC 825",
    portfolioUrl: "https://drive.google.com/file/d/1k17dithvtgosK2JfyLoLxD0gcWXmctzl/view",
  },
  {
    id: "hero-2",
    name: "Cao Thanh Hung",
    role: "Senior UX/UI Designer",
    headline: "VNG 출신 /n 시니어 UX/UI 디자이너",
    photo_url: "/no3.png",
    school: "Can Tho University",
    schoolElite: false,
    schoolTier: null,
    company: "VNG",
    companyElite: true,
    companyDomain: "vng.com.vn",
    yoeYears: 8,
    location: "베트남 호치민",
    skills: ["Figma", "Adobe Illustrator", "Design Systems", "User Research"],
    language: null,
    portfolioUrl: "https://drive.google.com/file/d/1DakTBaEIhZS6oyVEGB6XWuX2mcqD6yV4/view",
  },
  {
    id: "hero-3",
    name: "Phạm Gia Tuấn Khải",
    role: "AI/ML Engineer",
    headline: "RAG·AI Agent 전문 /n AI/ML 엔지니어",
    photo_url: "/Khai.jpeg",
    school: "University of Science, VNU-HCM",
    schoolElite: true,
    schoolTier: "top",
    company: "Aniday",
    companyElite: false,
    companyDomain: null,
    yoeYears: 1,
    location: "베트남 호치민",
    skills: ["AI Agent", "RAG", "Gemini API", "NLP", "Computer Vision"],
    language: "IELTS 8.0",
    portfolioUrl: "https://drive.google.com/file/d/1G3UVFJgQhCTyyB9VLARCEyoFjQvHhDOW/view",
  },
  {
    id: "hero-4",
    name: "Lê Vũ Đình Duy",
    role: "Full-stack Developer",
    headline: "핀테크·SaaS 경험 보유 /n 풀스택 개발자",
    photo_url: "https://twpxsbnkypocjfnerfmd.supabase.co/storage/v1/object/public/profiles/2d06a91c-3aaf-4fcc-aa9b-fecce6ea6516.jpg",
    school: "University of Science, VNU-HCM",
    schoolElite: true,
    schoolTier: "top",
    company: "FPT Software",
    companyElite: true,
    companyDomain: "fpt.com",
    yoeYears: 2,
    location: "베트남 호치민",
    skills: ["TypeScript", "NestJS", "React", "Next.js 14"],
    language: "영어 업무 가능 · 한국어 초급",
    portfolioUrl: "https://drive.google.com/file/d/1FASclI9U8_vwKEwR5BQEy3Q4r19do8lF/view",
  },
  {
    id: "hero-5",
    name: "Võ Minh Toàn",
    role: "Front End Developer",
    headline: "React·Vue /n 프론트엔드 엔지니어",
    photo_url: "/image_480.png",
    school: "Ho Chi Minh University of Technology",
    schoolElite: true,
    schoolTier: "top",
    company: "Moatable Inc.",
    companyElite: false,
    companyDomain: null,
    yoeYears: 3,
    location: "베트남 호치민",
    skills: ["React", "Vue", "Remix", "Pinia/Jotai"],
    language: "TOEIC 775",
    portfolioUrl: "https://drive.google.com/file/d/1gV-G-pF1srpe5pkdxMYbDS3Aq5CERLnB/view",
  },
  {
    id: "hero-6",
    name: "Nguyen Vu",
    role: "Senior Backend Developer",
    headline: "NAB 출신 /n 시니어 백엔드 엔지니어",
    photo_url: "/hero1.png",
    school: null,
    schoolElite: false,
    schoolTier: null,
    company: "NAB",
    companyElite: true,
    companyDomain: "nab.com.au",
    yoeYears: 5,
    location: "베트남 호치민",
    skills: ["Node.js", "NestJS", "PostgreSQL", "AWS", "Stripe"],
    language: "영어 업무 가능",
    portfolioUrl: "https://drive.google.com/file/d/1TVmqqdBUba1lIQ4CiiyxSDAVwTNApPDS/view?usp=drive_link",
  },
  {
    id: "hero-7",
    name: "Thai Bao Tran",
    role: "Growth Marketing",
    headline: "Mondelez·MoMo 출신 /n 그로스 마케터",
    photo_url: "/Thai_Bao_Tran.png",
    school: "Western Sydney University",
    schoolElite: false,
    schoolTier: null,
    company: "Mondelez",
    companyElite: true,
    companyDomain: null,
    yoeYears: 2,
    location: "베트남 호치민",
    skills: ["User Acquisition", "Performance Marketing", "Data Analytics", "GA4"],
    language: "IELTS 7.5",
    portfolioUrl: "https://mpzwzihqtbewqudpggam.supabase.co/storage/v1/object/public/ktc-cvs/1782462737036-ktb4ke4dll.pdf",
  },
  {
    id: "hero-8",
    name: "Phan Văn Tuyến",
    role: "Product Designer",
    headline: "프론트까지 이해하는 /n 시니어 프로덕트 디자이너",
    photo_url: "/phan-van-tuyen.png",
    school: null,
    schoolElite: false,
    schoolTier: null,
    company: "Envato Market",
    companyElite: false,
    companyDomain: null,
    yoeYears: 6,
    location: "베트남 호치민",
    skills: ["Figma", "Product Design", "React", "HTML/CSS"],
    language: null,
    portfolioUrl: "https://drive.google.com/file/d/1ohkC8b29V5LpJA4yRxxmqO1A3o_E8Eno/view",
  },
  {
    id: "hero-9",
    name: "Vũ Văn Tường",
    role: "Backend Software Engineer",
    headline: "삼성 R&D 출신 /n 시니어 백엔드 엔지니어",
    photo_url: "https://twpxsbnkypocjfnerfmd.supabase.co/storage/v1/object/public/profiles/3c462517-d45e-40be-810c-74e48061fb71.jpg",
    school: "Posts and Telecommunications Institute of Technology (PTIT)",
    schoolElite: false,
    schoolTier: null,
    company: "Samsung",
    companyElite: true,
    companyDomain: "samsung.com",
    yoeYears: 10,
    location: "베트남 하노이",
    skills: ["Golang", "Python", "Java", "Machine Learning", "LLM"],
    language: null,
    portfolioUrl: null,
  },
  {
    id: "hero-10",
    name: "Dang Van Y",
    role: "Senior UX/UI Designer",
    headline: "Prudential 출신 /n 시니어 프로덕트 디자이너",
    photo_url: "/no10.png",
    school: "Hoa Sen University",
    schoolElite: false,
    schoolTier: null,
    company: "Prudential",
    companyElite: true,
    companyDomain: "prudential.com",
    yoeYears: 14,
    location: "베트남 호치민",
    skills: ["Figma", "Adobe XD", "Design Systems", "Prototyping"],
    language: "영어 유창",
    portfolioUrl: "https://twpxsbnkypocjfnerfmd.supabase.co/storage/v1/object/public/resumes/09273709-87da-49be-9404-2c61f50b4a36/1782550641938_CV_-_Dangvany_-_Product_UIUX_Designer_-_Shupia.pdf",
  },
];
